development:
  adapter: postgresql
  encoding: utf8
  database: vilio_development
  host: localhost
  pool: 5
  username: vilio
  password: vilio
 
test:
  adapter: postgresql
  encoding: utf8
  database: vilio_test
  host: localhost
  pool: 5
  username: vilio
  password: vilio
 
production:
  adapter: postgresql
  encoding: utf8
  database: vilio_production
  pool: 5
  username:
  password: