development:
  adapter: postgresql
  encoding: utf8
  database: shepherd_development
  host: localhost
  pool: 5
  username: shepherd
  password: shepherd
 
test:
  adapter: postgresql
  encoding: utf8
  database: shepherd_test
  host: localhost
  pool: 5
  username: shepherd
  password: shepherd
 
production:
  adapter: postgresql
  encoding: utf8
  database: shepherd_production
  pool: 5
  username:
  password: