# Path on local file system to store uploaded files and
# all derivatives. The user account running rails must
# have write rights to this directory
files_path: '/srv/www/vilio-files/'

# Field types for metadata fields; add additonal types
# if desired
field_types: ['text', 'boolean', 'integer', 'date']
